FROM postgres:15.1

ENV POSTGRES_DB=wines
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234
ENV POSTGRES_HOST=postgres

COPY winewinewine.sql /docker-entrypoint-initdb.d/

EXPOSE 5432

CMD ["postgres"]